### PR TITLE
12-Bit Pipeline ADC for "Lab Bench on a Chip"--FAST-NUCES

### PR DESCRIPTION
**Pull request by Numanijaz99**

### CODE REVIEW

**Review by msaligane — CHANGES_REQUESTED** [review]
@Numanijaz99 Please rename your folder and files.

**Comment by Numanijaz99** [comment]
> @Numanijaz99 Please rename your folder and files.

Hi sir, I have renamed the folder and file please marge it. 
Thank you

**Comment by Numanijaz99** [comment]
Hi mahdi, i have renamed the folder and file but its still not merged. So
please merged it

Thank you.

**Comment by msaligane** [comment]
It is still not fixed. I will address it tomorrow.

**Comment by Numanijaz99** [comment]
please see here its shows that your folder and is renamed

**Review by msaligane — APPROVED** [review]

**Pull request merged**
