### PR TITLE
Proposal Submission: A Low Phase Noise Tunable Differential Clock Generator (PLL)

### PR DESCRIPTION
**Pull request by Engr-Azeem-Abbas**

### CODE REVIEW

**Review by msaligane — CHANGES_REQUESTED** [review]
@Engr-Azeem-Abbas Please remove spaces in your folder.

**Comment by Engr-Azeem-Abbas** [comment]
All spaces have been removed, Kindly merge it and let me know if any
further changes are required.
Thanks.

**Comment by msaligane** [comment]
@Engr-Azeem-Abbas I don't see your changes..

**Comment by Engr-Azeem-Abbas** [comment]
Please check now.

**Review by msaligane — APPROVED** [review]

**Pull request merged**
